site_name: wd-ott-checker
repo_url: https://github.com/digital-botanical-gardens-initiative/wd-ott-checker
site_url: https://digital-botanical-gardens-initiative.github.io/wd-ott-checker
site_description: These script aim to check for the presence of OTT ids for Wikidata taxa and eventually complete lacking information
site_author: Pierre-Marie Allard
edit_uri: edit/main/docs/
repo_name: digital-botanical-gardens-initiative/wd-ott-checker
copyright: Maintained by <a href="https://digital-botanical-gardens-initiative.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/digital-botanical-gardens-initiative/wd-ott-checker
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wd-ott-checker

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
